### PR TITLE
fix: include ewbank and uiaa fields in gql queries

### LINKED ISSUE #926: cannot view Ewbank grades
## Steps to Reproduce

1. Go to https://stg.openbeta.io/climbs/2d63fb47-b2eb-42f1-af9f-26d4b7a1ee5a (a climb in the "NZ test area" with Ewbank grade)
2. Note that you can't see the grade.
3. Note that you can update the grade, even though changes are not reflected after refreshing.

Likewise for an area containing Ewbank graded routes, like the parent https://stg.openbeta.io/crag/75be7758-98d9-5dd3-a1f5-6c6590b2d5aa

## Screenshots

image

image

## Expected Behavior

Should display the grade.

## Current Behavior

Can't see grades in front end if they are Ewbank (or likely any other than YDS, V, French, Font).
AU context boulder grades are ok - they use V scale.

Grades are stored and updated correctly in the backend.  See [hasura query](https://cloud.hasura.io/public/graphiql?endpoint=https%3A%2F%2Fstg-api.openbeta.io%2F&query=query+MyQuery+%7B%0A++area%28uuid%3A+%2275be7758-98d9-5dd3-a1f5-6c6590b2d5aa%22%29+%7B%0A++++id%0A++++climbs+%7B%0A++++++id%0A++++++grades+%7B%0A++++++++ewbank%0A++++++++font%0A++++++++french%0A++++++++uiaa%0A++++++++vscale%0A++++++++yds%0A++++++%7D%0A++++++gradeContext%0A++++++name%0A++++%7D%0A++%7D%0A%7D%0A)
```
query MyQuery {
  area(uuid: "75be7758-98d9-5dd3-a1f5-6c6590b2d5aa") {
    id
    climbs {
      id
      grades {
        ewbank
        font
        french
        uiaa
        vscale
        yds
      }
      gradeContext
      name
    }
  }
}
```
with output that contains the grades
```
{
  "data": {
    "area": {
      "id": "64b4ad4d0d9e63a7dc7fe50c",
      "climbs": [
        {
          "id": "2d63fb47-b2eb-42f1-af9f-26d4b7a1ee5a",
          "grades": {
            "ewbank": "34",
            "font": null,
            "french": null,
            "uiaa": null,
            "vscale": null,
            "yds": null
          },
          "gradeContext": "AU",
          "name": "climb one"
        },
        {
          "id": "6d5ea00e-89e7-49dd-bd59-88900b73b5ac",
          "grades": {
            "ewbank": "22",
            "font": null,
            "french": null,
            "uiaa": null,
            "vscale": null,
            "yds": null
          },
          "gradeContext": "AU",
          "name": "climb two"
        }
      ]
    }
  }
}
```

## Browser & version
Firefox 115.0.2 (64-bit)

## Operating system

ubuntu

### PR DESCRIPTION
**Pull request by vnugent**
---
name: Pull request
about: Create a pull request
title: ''
labels: ''
assignees: ''

---

## What type of PR is this?(check all applicable)
- [ ] refactor
- [ ] feature
- [x] bug fix
- [ ] documentation
- [x] optimization
- [ ] other

### Related Issues

Issue #926

### What this PR achieves
- Include ewbank and uiaa fields in GQL queries
- Create a reusable GQL fragment for GradeType so that it can be used in any queries 

### Screenshots, recordings
Screenshot 2023-07-20 at 5 54 02 PM

### CODE REVIEW

File: src/js/graphql/gql/tags.ts [hunk 1]
```diff
@@ -1,43 +1,6 @@
 import { gql } from '@apollo/client'
 import { EntityTag, TagTargetType, UserMedia } from '../../types'
 
-// Reusable fragments
-export const FRAGMENT_CLIMB_TAG = gql`
```
Comment (vnugent) [inline src/js/graphql/gql/tags.ts:5]: Old climb and area tag fragments no longer in use

**Review by musoke — APPROVED** [review]
Looks good!
