### PR TITLE
Address Overflow Issue

### LINKED ISSUE #678: Overflow issue user gallery page
This issue tracker is **ONLY** used for reporting bugs!

Horizontal scroll bar is visible when the screen size is below 1022px, Appears to be caused by long image captions.
http://localhost:3000/u/viet-test-profile

## Expected Behavior
Horizontal scrollbar should be hidden on small screen sizes.

## Possible Solution
add `overflow: hidden` to image container

## Steps to Reproduce
1. Navigate to user gallery page: http://localhost:3000/u/viet-test-profile
2. Make screen smaller than 1022px
3. Horizontal scroll bar should be visible. See Screen Shot.

Screen Shot 2023-02-01 at 1 38 35 PM

Image with `overflow: hidden` added to  the image container `<div class="relative"></dvi>`

Screen Shot 2023-02-01 at 1 38 43 PM

### PR DESCRIPTION
**Pull request by tedgeving**
Set a width on `Tag.tsx` component to make the text truncate properly.  
https://github.com/OpenBeta/open-tacos/issues/678

### CODE REVIEW

**Comment by vnugent** [comment]
###  Gallery view on mobile 
we use an entirely different card component for mobile: https://github.com/OpenBeta/open-tacos/blob/develop/src/components/media/MobileMediaCard.tsx#L19

Screen Shot 2023-02-04 at 9 31 19 AM

---
### Signed in / desktop
We should account for the X button when a user signs in and views their own profile

Screen Shot 2023-02-04 at 9 31 54 AM

**Comment by tedgeving** [comment]
@vnugent Let me know if those changes work for you. Normally I'd add a few css rules to sort this kind of issues out, or let me know if you think I should try a different approach.

File: src/components/media/Tag.tsx [hunk 1]
```diff
@@ -27,7 +30,8 @@ export default function Tag ({ tag, onDelete, size = 'md', showDelete = false, i
         onClick={stopPropagation}
       >
         {isArea && <MapPinIcon className='w-4 h-4' />}
-        <div className='mt-0.5 whitespace-nowrap truncate text-sm'>{name}</div>
+
+        <div style={maxWidth !== undefined ? { maxWidth: maxWidth } : { maxWidth: DEFAULT_TAG_WIDTH }} className='mt-0.5 whitespace-nowrap truncate text-sm'>{name}</div>
```
Comment (vnugent) [inline src/components/media/Tag.tsx]: what do you think if we just default max width to Tailwind `max-width-xs` which is 320?  And set `title` attribute to `name` to show a tool tip on desktop?  This way we don't have to introduce the maxWidth param?
```html
<div className='mt-0.5 whitespace-nowrap truncate text-sm max-w-xs ' title={name}>{name}</div>
```

https://tailwindcss.com/docs/max-width

File: src/components/media/Tag.tsx [hunk 2]
```diff
@@ -10,12 +9,16 @@ interface PhotoTagProps {
   isAuthorized?: boolean
   showDelete?: boolean
   size?: 'md' | 'lg'
+  maxWidth?: number
 }
 
-export default function Tag ({ tag, onDelete, size = 'md', showDelete = false, isAuthorized = false }: PhotoTagProps): JSX.Element | null {
+export default function Tag ({ tag, onDelete, size = 'md', showDelete = false, isAuthorized = false, maxWidth }: PhotoTagProps): JSX.Element | null {
```
Comment (vnugent) [inline src/components/media/Tag.tsx]: with `max-width-xs` set we don't have to introduce maxWidth param

**Review by vnugent — CHANGES_REQUESTED** [review]

File: src/components/media/Tag.tsx (hunk 1 above)
Comment (tedgeving) [reply src/components/media/Tag.tsx]: I looked into using that class an it is not narrow enough for some screen sizes and the small cards. 240px or so is the max width for several screen sizes and layouts.  See Screen Shot.

Maybe it would be better to limit the tag length on the admin side?  Or alternatively write a small utility function that truncates long tags?

Screen Shot 2023-02-08 at 7 22 07 PM

Comment (vnugent) [reply src/components/media/Tag.tsx]: Ah, you're right. In which case we can specify an arbitrary value directly in Tailwind: 

`max-w-[240px]`

This way we can keep all css within className (as much as possible).  The title attribute will enable a tool tip for those on desktop.

Comment (tedgeving) [reply src/components/media/Tag.tsx]: LOL, that was easy, first projects I've used tailwind on.  Nice feature, I've used Bootstrap for 10 plus years and it does not have anything similar.

Should be good to merge now.

File: src/components/media/Tag.tsx [hunk 3]
```diff
@@ -10,12 +9,16 @@ interface PhotoTagProps {
   isAuthorized?: boolean
   showDelete?: boolean
   size?: 'md' | 'lg'
+  maxWidth?: number
```
Comment (vnugent) [inline src/components/media/Tag.tsx]: can you remove this?

File: src/components/media/Tag.tsx [hunk 4]
```diff
@@ -10,12 +9,16 @@ interface PhotoTagProps {
...
 }
 
-export default function Tag ({ tag, onDelete, size = 'md', showDelete = false, isAuthorized = false }: PhotoTagProps): JSX.Element | null {
+export default function Tag ({ tag, onDelete, size = 'md', showDelete = false, isAuthorized = false, maxWidth }: PhotoTagProps): JSX.Element | null {
   const [url, name] = resolver(tag)
   if (url == null || name == null) return null
   const isArea = tag.destType === TagTargetType.area
+
+  const DEFAULT_TAG_WIDTH = 320
```
Comment (vnugent) [inline src/components/media/Tag.tsx]: can you remove?

File: src/components/media/Tag.tsx (hunk 2 above)
Comment (vnugent) [inline src/components/media/Tag.tsx]: please remove `maxWidth` prop

**Review by vnugent — CHANGES_REQUESTED** [review]

File: src/components/media/Tag.tsx (hunk 4 above)
Comment (tedgeving) [reply src/components/media/Tag.tsx]: done

File: src/components/media/Tag.tsx (hunk 2 above)
Comment (tedgeving) [reply src/components/media/Tag.tsx]: done

**Comment by vnugent** [comment]
Screen Shot 2023-02-10 at 1 40 57 PM
Screen Shot 2023-02-10 at 1 40 00 PM
