### PR TITLE
fix: don't use Next.js' Link to prevent prefetching

### LINKED ISSUE #860: Page not found after changing username
## Steps to Reproduce
1.  Log in
2. Go to profile -> Edit
3. Edit username and save
4. Being redirected back to the profile page but it's now a 404, not found

introduced by #838

### PR DESCRIPTION
**Pull request by vnugent**
Fix #860

### CODE REVIEW

File: src/components/users/account/UsernameChangeForm.tsx [hunk 1]
```diff
@@ -149,9 +150,7 @@ export const UsernameChangeForm: React.FC = () => {
         ? (<h1>Create a username</h1>)
         : (
           <>
-            <Link href={`/u/${username}`}>
-              <a className='link flex gap-2 items-center'><ArrowLeftCircleIcon className='w-5 h-5' />Back to profile</a>
-            </Link>
+            <a className='link flex gap-2 items-center' href={`/u/${username}`}><ArrowLeftCircleIcon className='w-5 h-5' />Back to profile</a>
```
Comment (vnugent) [inline src/components/users/account/UsernameChangeForm.tsx:153]: Switch to regular `a` tag instead Next.js `Link`.  Using `Link` will cause Next to prefetch the new profile page `/u/<new_username` as a user typing a new name.

**Review by vnugent — COMMENTED** [review]
.
